png(file="plot4.png",width=480, height=480)
par(mfrow=c(2,2))
x<-as.POSIXct(paste(mydata$V1, mydata$V2), format="%Y-%m-%d %H:%M:%S")
mydata$V3=as.integer(mydata$V3)
plot(x,mydata$V3,type = "l",ylab = "Global Active Power(kilowatts)",lty = 1)
lines(x,mydata$V3,lty = 1, lwd = 1)
mydata$V5=as.integer(mydata$V5)
plot(x,mydata$V5,type = "l",xlab="datetime",ylab = "Voltage",lty = 1)
lines(x,mydata$V5,lty = 1, lwd = 1)
plot(x,mydata$V6,type = "l",ylab = "Energy Meter Redading",lty = 1)
lines(x,mydata$V6,lty = 1, lwd = 1,col="black")
lines(x,mydata$V7,lty = 1, lwd = 1,col="red")
lines(x,mydata$V8,lty = 1, lwd = 1,col="blue")
legend("topright", legend=c("sub_metering_1", "sub_metering_2","sub_metering_3"),col=c("black","red", "blue"),lty=c(1,1,1))
mydata$V4=as.integer(mydata$V4)
plot(x,mydata$V4,type = "l",xlab="datetime",ylab = "Global_reactive_power",lty = 1)
lines(x,mydata$V4,lty = 1, lwd = 1)
dev.off()
